Repository AY2425S1-CS2103T-W10-4/tp, pull requests merged in 2024-11, with the labels that each got.

#127 Add scrolling mechanism to autocomplete and fix UI bugs
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MaxSizedContextMenu.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
Labels: alpha-bug

#136 Fix bug for edit and filter
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
Labels: alpha-bug

#129 Update UG with more comprehensive autocomplete explanations
  docs/Gemfile.lock
  docs/UserGuide.md
  docs/images/storeclass.png
Labels: type.Chore

#126 Add position checking to autocomplete
  src/main/java/seedu/address/logic/parser/AutocompleteParser.java
  src/test/java/seedu/address/logic/parser/AutocompleteParserTest.java
Labels: alpha-bug

#120 Update ug 1
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_config.yml
  docs/_layouts/default.html
  docs/images/StoreClass-Logo.png
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/commands/LoadCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Chore

#118 Update REGEX
  docs/UserGuide.md
  docs/images/UndoRedoExample1.png
  docs/images/UndoRedoExample2.png
  docs/images/UndoRedoExample3.png
  docs/images/UndoRedoExample4.png
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/commands/LoadCommand.java
  src/main/java/seedu/address/logic/parser/AutocompleteParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
  src/main/java/seedu/address/model/person/Module.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/GradeCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/DetailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/FilterPredicateTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/testutil/RandomPersonGenerator.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium

#151 Improve functionality of filter phone number
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/model/person/FilterPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
Labels: alpha-bug

#154 Fix Filter User Guide
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/FilterPredicate.java
Labels: alpha-bug

#168 Change autocomplete to be case-insensitive
  src/main/java/seedu/address/logic/parser/AutocompleteParser.java
Labels: alpha-bug

#170 Update user guide language to be more user-friendly
  docs/UserGuide.md
Labels: type.Chore

#165 Fix miscellaneous bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/GradeCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Module.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/GradeCommandTest.java
Labels: priority.High

#260 Update user guide examples under find and filter
  docs/UserGuide.md
Labels: severity.VeryLow
